kolplattformen/skolplattformen

- packages/api/lib/backend.js
- packages/app/components/children.component.js
- packages/app/components/classmates.component.js
- packages/app/components/contactMenu.component.js
- packages/app/components/login.component.js
- packages/app/components/newsItem.component.js
- packages/app/lib/backend.js
Now loads all information in the background and emits changes to the UI as soon as they arrive. Also load each child in parallel. 
Made som changes in code style to be more consistent and made it possible to press a row in classmates to open the menu.
> Feature/generators + minor fixes

- packages/site/assets/css/style.css
Fixes #29 
Remove text-selection from the animated shapes in the banner component.
> Remove text-selection from banner shapes

- packages/site/components/Banner.js
- packages/site/components/CtaTwo.js
- packages/site/components/Pricing.js
- packages/site/components/Testimonials.js
- packages/site/utils/intl.js
In this PR I fix two typos and handling of Swedish currency.
According to "Svenska skrivregler" there should be a `&nbsp;` between the value and the currency `kr`. By using the [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat) API we get the formatting for free.
> Fix typos and Swedish currency

- packages/site/assets/css/style.css
This PR fixes some accessibility issues. First, move the shape that was on top of the introduction text back in `z-index` to make the text more legible.
Second, remove the animation of the shapes and the iPhone if the user has set [`prefers-reduced-motion`](https://css-tricks.com/introduction-reduced-motion-media-query/).
> Remove animations for prefers-reduced-motion

- packages/app/components/child.component.js
- packages/app/components/newsListItem.component.js
This PR removes the "Publicerad på" in the news article subtitle and handles awkward line breaks in the tab navigation by auto-scaling the `font-size` if necessary.
Fixes #52 
| ![Skärmavbild 2021-02-08 kl  16 15 11](https://user-images.githubusercontent.com/1478102/107239322-0846e780-6a29-11eb-844a-7062fec5d504.png) | ![Skärmavbild 2021-02-08 kl  16 15 23](https://user-images.githubusercontent.com/1478102/107239325-08df7e00-6a29-11eb-98c9-19f698332dd5.png) |
> fix: handle line breaks in tab navigation

- packages/app/components/contactMenu.component.js
This PR changes the phone icon to the more-icon, the three dots, that most users should be familiar with from other apps. We also visually hide any contact information that is unavailable as well as handle click inside the contact menu better.
Fixes #48 
| ![Skärmavbild 2021-02-09 kl  08 40 52](https://user-images.githubusercontent.com/1478102/107330980-8e5b4080-6ab2-11eb-85b7-0005d5d7e7d0.png) | ![Skärmavbild 2021-02-09 kl  08 40 36](https://user-images.githubusercontent.com/1478102/107330978-8d2a1380-6ab2-11eb-9904-13c4a6ce0c3a.png) |
> fix: contact page issues

- packages/app/components/login.component.js
- packages/app/ios/Podfile.lock
In #59 I didn't catch the case where the social security number was `undefined` (not entered) or invalid (while typing). This PR checks the validity of the social security number before parsing it.
> fix: handle missing social security number

- packages/app/components/calendar.component.js
This PR removes clicks from calendar items by adding the `disabled` prop. It also changes the date handling to `fromNow` instead of `calendar`. `calendar` formats the date separately when the date is close in time, but we only have the date as `YYYY-MM-DD` so we gain nothing from this formatting. The difference can be seen in the screenshots.
Fixes #51 
| ![Skärmavbild 2021-02-10 kl  09 13 45](https://user-images.githubusercontent.com/1478102/107482734-64704f80-6b80-11eb-975a-be26084e16ec.png) | ![Skärmavbild 2021-02-10 kl  09 13 55](https://user-images.githubusercontent.com/1478102/107482743-663a1300-6b80-11eb-95eb-92ff8a73cbe9.png) |
> fix: handle dates and clicks on calendar items

- packages/app/components/child.component.js
- packages/app/components/classmates.component.js
- packages/app/components/newsList.component.js
- packages/app/components/notificationsList.component.js
This PR separates all screens for a child on separate routes. It seems like they were dependant on the height of each other before. This way layout is handled correctly without overflowing the `<SafeAreaView>` and without hacky `paddingBottom` adjustments.
The screenshots illustrate what the screen looked/look like when scrolled to the bottom.
Fixes #49, fixes #50 
| ![Skärmavbild 2021-02-10 kl  10 49 42](https://user-images.githubusercontent.com/1478102/107493290-b9669280-6b8d-11eb-9e46-25338b0323b7.png) | ![Skärmavbild 2021-02-10 kl  10 48 53](https://user-images.githubusercontent.com/1478102/107493262-b370b180-6b8d-11eb-9a52-7980fdb1ecd7.png) | 
| ![Skärmavbild 2021-02-10 kl  10 49 38](https://user-images.githubusercontent.com/1478102/107493288-b …
> fix: scroll overflow on child screens

- packages/app/components/login.component.js
This PR adds a couple of fixes to the login screen:
- Handle the title not wrapping correctly by adding `adjustFontSizeToFit`
- Change title to "Öppna Skolplattformen"
- Add call to `Keyboard.dismiss` which hides the keyboard when clicking outside
- Remove easter egg navigation when clicking on the image
- Flexbox fix to make `<KeyboardAvoidingView>` work correctly
Fixes #68
> fix: login screen issues

- packages/site/assets/css/style.css
- packages/site/components/Footer.js
This adds the email address to the site footer. It also cleans up the footer code from unused social media links, a broken background, and more minor fixes.
Fixes #67
> feat: add email on site

- packages/site/components/Layout.js
Noticed when sharing the link on Slack that it didn't expand the URL, due to missing OG metadata - added it here.
1. came up with a random description, feel free to change :)
2. took the best image I could find (logo from the header), but would probably be nicer with a custom one with a phone + app?
> feat: add Open Graph title, image and description

- packages/app/components/child.component.js
- packages/app/components/childListItem.component.js
Den här PRn fixar direktlänkning via knapparna i footern på ett barn i listan (se skärmdump) till rätt undervy inne på ett barns information.
Fixes #101
> fix: direktlänkning från knapparna i barnlistan

- packages/app/components/childListItem.component.js
Den här PRn löser ett problem för första generationens iPhone SE där lång namn sträckte sig utanför skärmen. Har även tajtat till avstånden i headern något vilket ger bättre utseende och mer utrymme.
Fixes #104 
| ![Skärmavbild 2021-02-15 kl  08 19 58](https://user-images.githubusercontent.com/1478102/107916789-310a3800-6f67-11eb-9406-e200d2528586.png) | ![Skärmavbild 2021-02-15 kl  08 19 40](https://user-images.githubusercontent.com/1478102/107916785-2fd90b00-6f67-11eb-8f47-7f19c237ca17.png) |
> fix: hantera långa namn i barnlistan

- packages/app/App.js
Denna PR fixar förhoppningsvis #103. Den gör så att statusfältet alltid ska ha mörkt innehåll.
> fix: använd statusfält med mörkt innehåll

- .github/workflows/pr_check.yml
- .github/workflows/release.yml
- packages/app/components/__tests__/Notification.test.js
- packages/app/components/notification.component.js
- packages/app/package.json
- packages/app/yarn.lock
Den här PRn gömmer datumet om det saknas i en avisering. Den gör att vi inte får det trasiga UI:t med tomma parenteser i #99 men löser **inte** den underliggande buggen att datumet saknas.
Jag har också lagt till de första testerna och setup för dem i appen. Testerna körs i `jest` och använder `@testing-library/react-native`.
> fix: hantera ui för saknade datum i aviseringar

- packages/app/components/__tests__/Children.test.js
- packages/app/components/__tests__/Notification.test.js
- packages/app/components/childListItem.component.js
- packages/app/components/children.component.js
- packages/app/package.json
- packages/app/setupTests.js
- packages/app/utils/testHelpers.js
Den här PRn lägger till ett "empty state"-meddelande när barn saknas för den som har loggat in så de inte bara får en tom vit skärm.
Den uppdaterar också barnlistan till att använda `<List>` vilket kommer ge bättre visning för de som har fler barn än 2-3. För övriga ger det ett kompaktare och överskådligare gränssnitt när det inte finns några kalenderevent eller notifieringar.
| ![Skärmavbild 2021-02-15 kl  15 37 23](https://user-images.githubusercontent.com/1478102/107961548-5b2f1a80-6fa6-11eb-872d-c5f4d016bf84.png) | ![Skärmavbild 2021-02-15 kl  15 37 06](https://user-images.githubusercontent.com/1478102/107961545-59fded80-6fa6-11eb-875f-6a8b7a631935.png) | 
| ![Skärmavbild 2021-02-15 kl  15 49 …
> feat: lägg till empty state för barnlistan

- packages/site/components/AppShots.js
- packages/site/components/Testimonials.js
Genom att använda `next/image` så får vi lazy loading och bildoptimisering inbyggt. Det ger också en liten bump i performance i Lighthousetester.
> chore(site): använd next/image för bilder

- packages/site/components/Testimonials.js
- packages/site/components/__tests__/Banner.test.js
- packages/site/components/__tests__/DownloadButtons.test.js
- packages/site/components/__tests__/Testimonials.test.js
Den här PRn fixar texten för Karins testimonial. Den lägger även till tester för `<Testimonials>` och `<DownloadButtons>`.
> fix: uppdatera testimonial med rätt text

- packages/app/android/app/src/main/AndroidManifest.xml
- packages/app/app.json
- packages/app/components/login.component.js
- packages/app/components/navigation.component.js
- packages/app/ios/app/AppDelegate.m
- packages/app/ios/app/Info.plist
Added support for deep-linking with the prefix of "oppnaskolplattformen://" and added that url to the BankID-url. I'm not a parent so I can't really test to see if this works, but the deep-linking works so it shouldn't be any issues.
Closes #129
> Feature: automatic redirect from BankID on iOS

- packages/app/App.js
Efter vi uppdaterade statusbar för iPhone till att använda mörkt innehåll i #122 så blev texten mörk på mörk bakgrund i Android. Denna PRn ger även Android mörk text på vit bakgrund.
| ![Screenshot_1613725186](https://user-images.githubusercontent.com/1478102/108482287-975dc600-7299-11eb-88aa-05ad2b73b308.png) | ![Screenshot_1613724847](https://user-images.githubusercontent.com/1478102/108482291-988ef300-7299-11eb-9d02-3e6630f28e2b.png) |
> fix(android): uppdatera färg på statusbar

- .github/workflows/pr_check.yml
- .github/workflows/release.yml
- packages/app/components/__tests__/NewsItem.test.js
- packages/app/components/newsItem.component.js
Detta är en follow-up till #110 där tomma datum gömdes i nyheterna. Om datumet fanns men hade fel format så gömdes det inte, t.ex. `2020-08-16T21:10:00.000+02:0`. Den här PRn tar hand om saknade datum och felaktiga format genom att först försöka parsea datumet. Jag har även lagt till tester för hela `<NewsItem>`.
> fix: göm ogiltiga datum i nyheter

- packages/app/components/markdown.component.js
The "src" of images in news was always prepended by the host name of skolplattformen, breaking images where the src was a complete url. This PR fixes the issue. Only when the src starts with "/" it's prepended, otherwise it's left as it is.
> fix: hantera bilder med absolut url i markdown

- packages/app/components/__tests__/NewsItem.test.js
- packages/app/components/newsItem.component.js
Den här PRn uppdaterar styling av en nyhetssida. Den fixar till ett gäng textstorlekar för att lägga mindre tyngd vid vissa delar och flyttar även ner bilden efter texten. Den hanterar även datum genom att första köra dem genom `moment().isValid()` för att verkligen se om datumet går att parsea.
Fixes #76 i alla fall som en enkel lösning att först och främst visa textinnehållet och sekundärt visa bilden.
| ![Simulator Screen Shot - iPhone 11 - 2021-02-20 at 14 05 16](https://user-images.githubusercontent.com/1478102/108596392-0106ce80-7385-11eb-82e0-a7282292e00e.png) | ![Simulator Screen Shot - iPhone 11 - 2021-02-20 at 14 04 25](https://user-images.githubusercontent.com/1478102/108596389-ff3d0b00-7384-11eb-81cc-636d51a112aa.png) |
> chore: uppdatera styling för en nyhet

- packages/app/components/childListItem.component.js
- packages/app/components/children.component.js
Den här PRn fixar scroll i barnlistan och flyttar frånvaroknappen in i innehållet istället för efter footern.
| ![Simulator Screen Shot - iPhone 11 - 2021-02-21 at 07 52 23](https://user-images.githubusercontent.com/1478102/108617857-c13df680-7419-11eb-849a-550109aad199.png) | ![Simulator Screen Shot - iPhone 11 - 2021-02-21 at 07 51 27](https://user-images.githubusercontent.com/1478102/108617835-9fdd0a80-7419-11eb-8c89-90fda7679e76.png) |
> fix: scroll i barnlistan och flytta frånvaroknapp

- packages/app/android/app/build.gradle
RN can't handle varying appllicationIds when launching. Removing this so
the app is launched correctly with yarn run android
✅ Closes: #130
> fix: 🐛 remove applicationSuffix for Android debug variant

- .github/workflows/release.yml
- .releaserc
Eftersom vi redan använder `semantic-release`-commits så kan vi enkelt få en changelog som uppdateras med ändringar efter bygge i `main`.
Skapades med hjälp av [`supreme github-actions --no-npm`](https://github.com/opendevtools/supreme#github-actions) och justerades in i vår befintliga `release.yml`
> chore: automatiskt changelog via semantic-release

- packages/site/components/Footer.js
Tjenixen,
Här kommer en minifix från Medelpad. Riktigt bra jobbat med detta. :)
Det var inte tydligt att github var en länk i footern tidigare. Visade sig att det räckte med ett byte till `Link.External` istället för en vanlig `<a>`.
/J
> fix: använd korrekt komponent för github-länk

- packages/app/components/login.component.js
Trots allt fina jobb av @arvidnilber i #139 så var autostarttoken alltid "undefined" och redirect funkade inte från BankId appen.  Den här lilla fixen fixar det!
> fix: 🐛 Redirect från BankId appen funkar nu

- packages/site/components/FunFacts.js
Hej,
Nu skrivs det ut 1000000000, vilket gör det svårt att se exakt hur mycket pengar som Stockholms stad har lagt på denna 🔥.
Ändrade till 1 000 000 000 så att det är lättare att se.
- Minskade typografin på mobil för att fungera på 320px bred skärm
- La till whitewrap-no-wrap så att det inte hoppar omkring
/J
> fix: använd korrekt tusen-separator för miljarden

- packages/app/components/login.component.js
- packages/app/package.json
- packages/app/yarn.lock
Om `API-Key`-headern finns med i `CreateItem`-anropet får man en 403:a
> fix: 🐛 Fixar senaste blocken

- packages/app/components/newsListItem.component.js
Bilderna i nyhetsflödet tar upp mycket plats på mindre enheter. Den här PR:n gömmer bilderna om bredden på enheten är 320 eller mindre.
Fixes #198 
| iPhone SE | iPhone 11 |
| ![Simulator Screen Shot - iPhone SE (1st gen) - 2021-03-25 at 13 00 07](https://user-images.githubusercontent.com/1478102/112471324-084a3f00-8d6c-11eb-9f46-c8a9ef3c1a39.png) | ![Simulator Screen Shot - iPhone 11 - 2021-03-25 at 13 00 09](https://user-images.githubusercontent.com/1478102/112471316-06807b80-8d6c-11eb-9867-5cf62b6b8c64.png) |
> fix: göm bilder i nyhetslistan för mindre enheter

- packages/app/components/children.component.js
- packages/app/components/login.component.js
- packages/app/components/navigation.component.js
Den här PRn separerar navigationen i två separata "stackar". Detta gör att det inte går att råka navigera tillbaka till inloggningssidan genom att svepa till höger.
> fix: separera navigation i två olika stackar

- packages/app/jest.config.js
Den här PR:n tar bort ett gäng moduler från `transformIgnorePatterns` i vår Jest-konfiguration
> chore(jest): ta bort oanvända transformIgnorePatterns

- packages/app/components/__tests__/saveToCalendar.test.js
- packages/app/components/saveToCalendar.component.tsx
Den här PRn tar bort `notes` när användaren sparar till kalendern. Jag har ingen bra data på vad `description` (fältet som används för `notes`) i ett kalenderevent kan innehålla från API:et, men enligt #188 kan det förekomma HTML. De flesta använder antagligen inte anteckningar och om de gör det så vill de säkert fylla i det själva.
Fixes #188
> fix: ta bort anteckningar från kalenderevent

- packages/app/components/absence.component.tsx
- packages/app/components/auth.component.tsx
- packages/app/components/child.component.tsx
- packages/app/components/childListItem.component.tsx
- packages/app/components/children.component.tsx
- packages/app/components/login.component.tsx
- packages/app/components/newsListItem.component.tsx
- packages/app/components/notification.component.tsx
- packages/app/package.json
- packages/app/styles/colors.ts
- packages/app/styles/index.ts
- packages/app/styles/layout.ts
- packages/app/styles/sizing.ts
- packages/app/styles/typography.ts
- packages/app/yarn.lock
Appen har spretig styling i vissa delar, t.ex. margin-värden som bara används på ett ställe. Vi har också styling för färger och typografi som återanvänds på flera ställen som kan samlas i ett designsystem. Den här PR:n lägger till ett system som är inspirerat av [Thoughbots React Native styling](https://github.com/thoughtbot/react-native-typescript-styles-example) och storlekar från Tailwind (som vi använder i `site`). Tanken är att bygga en atomic styling som enkelt kan pusslas ihop till exporterade komponenter när vi ser att något återanvänds.
På sikt tänker jag att detta helt kan ersätta vår användning av `ui-kitten` vilket ger oss större kontroll över hur vi vill att appen ska se ut.
Designsystemet har bara påbörjats och alla filer har inte migrerats till det, men jag tänker att det …
> refactor(app): lägg till designsystem

- packages/site/components/NavLinks.tsx
- packages/site/components/TimelineLatest.tsx
- packages/site/data/timelineEvents.tsx
- packages/site/next.config.js
- packages/site/pages/aktuellt.tsx
Den här PR:n byter namn för tidslinjen från "Media & Historia" till "Aktuellt". Den är också ordningen till senast först.
> chore(site): byt ordning på tidslinje och namn till aktuellt

- packages/site/next.config.js
Använd `redirects` istället för `rewrites` för historia -> aktuellt vilket ger en snyggare omskrivning av länkarna till gamla.
> chore: använd redirect istället för rewrite

- packages/site/components/NavLinks.tsx
This mainly makes the cursor into a pointer, which is always a nice feedback for seeing users.
> fix: förbättra tillgänglighet för länkar i navigering

- packages/app/components/childListItem.component.tsx
- packages/app/ios/Podfile.lock
- packages/app/package.json
- packages/app/yarn.lock
Den här PR:n uppdaterar `embedded-api` till `v3.0.1` som innehåller fixar för datumhantering. Den fixar också en varning från `moment` som kom från att vi inte skicka något datum att jämföra med till `isSame`:
```js
// Vi hade
moment(date).isSame('week')
// Det ska vara
moment(date).isSame(moment(), 'week')
```
> fix: fel i datumhantering

- packages/app/components/__tests__/Children.test.js
- packages/app/components/childListItem.component.tsx
- packages/app/components/modalWebView.component.tsx
- packages/app/components/notification.component.tsx
Fixar #192 genom att tillåta sharedCookies på webvyn. 
Unikum använder SSO som funkar såhär:
1. Länken i notfieringen går till start.unikum.net. 
2. Redirect till login001.stockholm.se. Här behövs SMSESSION cookien för att komma vidare
3. Ett formulär skickas tillbaka som webläsaren auto-postar (med Javascript) tillbaka till start.unikum.net
4. Nu får man en login-cookie från Unikum och allt rullar på
Det enklaste sättet att få det att funka var att tillåta delade cookies på WebView och sen låta allt funka automatiskt.
Funkar i IOS, har inte testat på Android (har ingen miljö uppsatt)
> Add property to enable shared cookies on webview (fix #192 SSO mot Unikum)

- packages/app/components/calendar.component.tsx
Lade till datum i kalendervyn. Att bara se att skolan stänger 15:45 om en månad kändes som för lite information. Merga om det känns vettigt.
Före: "om en månad"
Efter: "2021-04-30 (om en månad)"
> feat: 🎸 Datum i kalendern

- packages/app/components/childListItem.component.tsx
På förstasidan la jag till nyheter för den här veckan. Jag ändrade även så kalender och schema visar 7 dagar framåt istället för samma vecka. Ofta sitter man på söndag kväll och tittar framåt för att planera veckan. 
Jag la även till prefix (Nyhet: , Avisering:) och datum.
Det blir kladdigt, bättre ux behövs, men det är good enough just nu kan jag tycka.
> feature: Skriv även ut nyheter i listan på ett barn

- packages/app/components/children.component.tsx
On the "settings" panel the translations did not update if you had logged out and changed language, this is because the settingsOptions was outside the component so it did not update.
> fix: 🐛 Settings menu was not updated on language change

- packages/app/components/setLanguage.component.tsx
On Android the save button was under the navigation bar in language selection
> Fix save button placement in language on Android

- packages/site/components/Banner.tsx
Shape was over button so you couldn't interact with button where the shape was.
> chore(a11y): move shape that interferes button

- packages/site/components/Banner.tsx
This adds some spacings between the "The app is free" text and the introduction
| ![Skärmavbild 2021-04-23 kl  11 33 13](https://user-images.githubusercontent.com/1478102/115851908-c45c5f80-a427-11eb-95be-be37be0f5b87.png) | ![Skärmavbild 2021-04-23 kl  11 34 13](https://user-images.githubusercontent.com/1478102/115851978-d938f300-a427-11eb-8f3f-7f4c5ee3e019.png) |
> chore(site): add spacing for patreon text

- packages/app/components/modalWebView.component.tsx
The modal was using `SyntheticEvent`, which does not exist in `react-native`. This imports the correct type from the `react-native-webview` instead.
> chore(app): fix type for modal onLoad

- packages/app/components/week.component.tsx
Jag lade till formatering som försvann från schemat i och med att <Text> -taggen infördes istället för strängar.
> fix: 🐛 formattering av schema som försvann är tillbaka

- packages/app/services/languageService.ts
Fallback till svenska på ord som inte finns i en översättning.
> fix: 🐛 Ord som inte är översatta hämtas från svenska

- packages/app/components/tabBarLabel.component.tsx
> fix: 🐛 Fixes long navigation names in tab bar

- packages/app/components/tabBarLabel.component.tsx
> fix: fontSize on tabBarLabel decreased

- .gitignore
- packages/app/components/setLanguage.component.tsx
En bugg i react-native-gesture-handler gjorde att det inte gick att ändra språk på android.
> fix: 🐛 Välja språk på Android var trasigt

- packages/app/components/week.component.tsx
* Skriver inte ut tomma parenteser om det inte finns något klassrum/location för en lektion
* Matsedel skrivs ut även om koden är i versaler (eller annat case)
> fix: 🐛 Småfixar i schemat

- apps/skolplattformen-sthlm/components/image.component.tsx
- apps/skolplattformen-sthlm/components/markdown.component.tsx
- apps/skolplattformen-sthlm/components/newsItem.component.tsx
- apps/skolplattformen-sthlm/components/newsListItem.component.tsx
- libs/api-skolplattformen/lib/fakeData.ts
> fix: images cropping on different devices

- libs/hooks/src/useCalendar.test.js
- libs/hooks/src/useChildList.test.js
- libs/hooks/src/useClassmates.test.js
- libs/hooks/src/useEtjanstChildren.test.js
- libs/hooks/src/useMenu.test.js
- libs/hooks/src/useNews.test.js
- libs/hooks/src/useNewsDetails.test.js
- libs/hooks/src/useNotifications.test.js
- libs/hooks/src/useSchedule.test.js
- libs/hooks/src/useSkola24Children.test.js
- libs/hooks/src/useTimetable.test.js
- libs/hooks/src/useUser.test.js
The jest.advanceTimersToNextTimer() is not needed by the tests, they pass without it.
The reason the warnings was not seen before was because we used an older version
of jest (26) before. Now with NX we use 27.
> test: 💍 Remove warnings about timers not beeing mocked

- apps/skolplattformen-sthlm/components/week.component.tsx
- apps/skolplattformen-sthlm/services/languageService.ts
- apps/skolplattformen-sthlm/utils/translation.ts
När locale i moment heter annorlunda än landskoden så används rätt namn, annars används svenska
> fix: 🐛 Fixar krasch när ett språks locale inte finns i moment

- libs/api-hjarntorget/lib/apiHjarntorget.ts
Tries to work around issue #559 by showing the unassociated messages under News instead.
> Make messages not specific to one child be treated as news

- apps/website/components/FunFacts.tsx
- apps/website/components/Pricing.tsx
- apps/website/components/QA.tsx
- apps/website/tailwind.config.js
**What's the problem(s)?**
- Missing style for h4 in dark mode.
- Inconsistent pricing; 11 or 12 kronor.
- Incorrect anchor for contact email.
**What's changed?**
- Use `price` constant where we output the current app price.
- Update the contact email anchor.
- Add missing style for h4 in dark mode.
**How can this be verified?**
- Tested locally.
> Fix: Styles, pricing & contact email

- apps/api-test-app/src/main.js
- libs/api-hjarntorget/lib/apiHjarntorget.ts
Adds support for using api-hjarntorget to fetch things with api-test-app.
> Add support for running api-test-app with api-hjarntorget

- apps/skolplattformen-app/components/children.component.tsx
✅ Closes: #571
Vit text på vit bakgrund gjorde att texten när man loggar in men inte har barn i systemet inte syntes.
> fix: 🐛 Ingen text syns i dark mode när inga barn hittas

- libs/api-hjarntorget/lib/fake/lessons.ts
Det finns bara schema för en dag för Hjärntorgets testanvändare
Denna fix anpassar dagen som lektionerna visas på, så att dagen växlar till nästa efter kl 18 vardagar och till måndag om det är helg.
Så lektionerna borde nu dyka upp i schemat även under helgen.
> fix: 🐛 Flyttar offset för lektioner i fakeData för Hjärntorget

- apps/skolplattformen-app/components/week.component.tsx
- apps/skolplattformen-app/package.json
> fix: 🐛 Hide lunch in timetable if not showing current week

- apps/skolplattformen-app/components/week.component.tsx
Dates were wrong in Timetable in some languages. This forces the week to always start at Monday (since skolplattformen's week start on Monday)
> fix: 🐛 Week starts on monday regardless of selected locale

- apps/skolplattformen-app/components/child.component.tsx
- apps/skolplattformen-app/components/childListItem.component.tsx
- apps/skolplattformen-app/components/navigationTitle.component.tsx
https://github.com/kolplattformen/skolplattformen/assets/98584401/d06714f8-ac23-4ec1-8d10-b7226614b445
#483
> feat: navigate from "Your Children" to specific tabs
