kolplattformen/skolplattformen

- packages/site/components/FunFacts.js
Hittade några fler stavfel igår, men verkar som att någon annan hann täppa till dem innan jag hittade rätt repo :) Kul projekt!
> Fix 'orginalet' front-page typo

- README.md
This PR adds links to the contributor's profile pages. It also fixes my last name to **Natt och Dag**.
> docs: add contributor profile links and fix my last name

- packages/site/assets/css/style.css
- packages/site/components/Banner.js
- packages/site/components/CtaThree.js
- packages/site/components/CtaTwo.js
- packages/site/components/Features.js
- packages/site/components/Pricing.js
- packages/site/components/__tests__/Banner.test.js
This PR adds a link to the app on the App Store.
> feat: add app store link

- packages/site/components/Media.js
- packages/site/pages/index.js
(See #36)
I don't have much experience with React but I hope this can at least
provide a starting point.
I'm not sure which links to include but that's easy to change of course.
> Add a simple media links section

- packages/site/components/__tests__/Banner.test.js
Den här PRn fixar testerna för `<Banner>`
> test: fixa tester för banner

- packages/site/components/CtaThree.js
- packages/site/components/CtaTwo.js
- packages/site/components/DownloadButtons.js
Added download buttons both for App Store and Goole Play after each CTA block
> fix: Activate all download buttons

- packages/app/components/newsItem.component.js
- packages/app/components/newsListItem.component.js
Visar datum på nyhetslistan
och i artikeln:
Fixes #108
> Fix: Datum på nyheter

- packages/site/components/QA.js
> fix: removed texts - app isnt released and added section for bug reporting 

- packages/app/components/login.component.js
> fix: 🐛 properly load the SSN from the cache

- packages/app/.prettierrc
- packages/app/.prettierrc.js
- packages/app/App.js
- packages/app/components/__tests__/Notification.test.js
- packages/app/components/calendar.component.js
- packages/app/components/child.component.js
- packages/app/components/childContext.component.js
- packages/app/components/childListItem.component.js
- packages/app/components/children.component.js
- packages/app/components/classmates.component.js
- packages/app/components/contactMenu.component.js
- packages/app/components/image.component.js
- packages/app/components/login.component.js
- packages/app/components/markdown.component.js
- packages/app/components/modalWebView.component.js
- packages/app/components/navigation.component.js
- packages/app/components/newsItem.component.js
- packages/app/components/newsList.component.js
- packages/app/components/newsListItem.component.js
- packages/app/components/notification.component.js
- packages/app/components/notificationsList.component.js
- packages/app/package.json
- packages/app/yarn.lock
Den här PRn lägger till samma `prettier` setup som vi har i `site` även i appen. Jag har sen kört `npx prettier -w components/**/*.js *.js` för att fixa våra filer. Jag gick även igenom alla komponenter och tog bort oanvänd kod.
> chore(app): lägg till prettier och ta bort oanvänd kod

- README.md
- packages/app/README.md
- packages/site/README.md
Den här PRn uppdaterar dokumentationen med hur du kommer igång med utveckling av `app` och `site`
Fixes #118
> docs: uppdatera dokumentation

- packages/app/components/__tests__/Notification.test.js
- packages/app/components/notification.component.js
Made it look more like the news, took the styles from news. Maybe these styles should be higher up? idk
> style: notifaction

- packages/app/components/__tests__/Children.test.js
- packages/app/components/childListItem.component.js
Not sure about the copy. Looked kinda broken first time I used it.
> fix: looked broken when no new event

- packages/app/components/__tests__/ContactMenu.test.js
- packages/app/components/absence.component.js
- packages/app/components/calendar.component.js
- packages/app/components/child.component.js
- packages/app/components/childListItem.component.js
- packages/app/components/children.component.js
- packages/app/components/classmates.component.js
- packages/app/components/contactMenu.component.js
- packages/app/components/icon.component.js
- packages/app/components/login.component.js
- packages/app/components/modalWebView.component.js
- packages/app/components/newsItem.component.js
- packages/app/components/newsList.component.js
- packages/app/components/notification.component.js
- packages/app/components/notificationsList.component.js
Den här PRn...
- städar bort oanvänd kod
- flyttar ut ikoner till en samlad komponentfil
- lägger till tester för `<ContactMenu>`
> refactor(app): städa upp kod

- packages/app/components/login.component.js
La till så att bankid-inloggningen avbryts om man trycker på avbryt.
closes #208
> fix: avbryt bankid-inloggning

- packages/site/components/Banner.js
- packages/site/components/NavLinks.js
- packages/site/components/__tests__/AppShots.test.js
- packages/site/components/__tests__/Banner.test.js
- packages/site/components/__tests__/DownloadButtons.test.js
- packages/site/components/__tests__/Header.test.js
- packages/site/components/__tests__/Testimonials.test.js
- packages/site/content/locale/en.js
- packages/site/content/locale/index.js
- packages/site/content/locale/sv.js
- packages/site/next.config.js
- packages/site/package.json
- packages/site/pages/_app.js
- packages/site/utils/test-utils.js
- packages/site/yarn.lock
Doing a minor pull request, prior to actually translating the entire site in one large commit.
* Added react-intl
* next-config for dynamic routing (sv, en etc)
* Language files (en + sv)
> Add support for internationalization

- packages/site/components/ButtonLink.tsx
> chore: ta bort console.log

- packages/app/components/markdown.component.tsx
> fix: länkar i markdown

- packages/app/App.js
- packages/app/__mocks__/react-native-safe-area-context.js
- packages/app/components/auth.component.tsx
- packages/app/components/children.component.tsx
- packages/app/components/newsItem.component.tsx
- packages/app/components/safeAreaViewContainer.component.tsx
- packages/app/ios/Podfile.lock
- packages/app/package.json
- packages/app/yarn.lock
* Added SafeAreaProvider
* Added a  resusable safeAreaViewContainer.component that takes in account for the statusbar in Android...
* ... which I end up not using, but using the inset hook on children.component instead due to the reason that there was also a bug where the safe area added a white border in the bottom, even though the page is grey.
* Added safeAreaViewContainer to newsItem.component and auth.component
Screenshot from both apps
✅ Closes: #180
> fix: 🐛 Fixes issue where settings icon was hidden on Android

- packages/app/App.js
- packages/app/components/__tests__/Menu.test.js
- packages/app/components/child.component.tsx
- packages/app/components/childListItem.component.tsx
- packages/app/components/menu.component.tsx
> style: 💄 Change meny to matsedel

- packages/site/data/timelineEvents.tsx
> feat(site): uppdatera timeline med april

- packages/site/.eslintrc.json
- packages/site/next.config.js
- packages/site/package.json
- packages/site/yarn.lock
This PR add TypeScript handling to the ESLint setup in `site`.
> chore(site): fix eslint

- packages/site/data/timelineEvents.tsx
Add news articles from Ny Teknik (2021-04-15) and DN (2021-04-15)
> chore: add news articles

- packages/site/data/timelineEvents.tsx
Add podcast episode from "Allt du behöver veta om ny teknik"
> chore: add podcast

- packages/app/components/loading.component.tsx
- packages/app/context/language/languageContext.tsx
- packages/app/services/languageStorage.ts
- packages/app/utils/testHelpers.tsx
Had an issue where language was not saved after restarting the app. This is now fixed.
✅ Closes: #280
> fix: 🐛 Fixes issue where locale was not saved

- packages/site/components/Status.tsx
- packages/site/pages/status.tsx
Page where we can redirect users when the app does not work for some
reason.
> feat: 🎸 Add new Status page

- packages/app/ios/Podfile.lock
- packages/app/ios/app.xcodeproj/project.pbxproj
- yarn.lock
> chore: 🤖 Updates pbxproj and yarn + podfile locks

- packages/app/App.js
- packages/app/components/__tests__/Children.test.js
- packages/app/components/children.component.tsx
- packages/app/translations/en.json
- packages/app/translations/sv.json
When loading children and something goes wrong, display an errormessage
and a link to our statuspage
✅ Closes: #195
> feat: 🎸 Add errormessage to loading page

- packages/app/components/setLanguage.component.tsx
- packages/app/services/languageService.ts
- packages/app/translations/pl.json
- packages/app/utils/translation.ts
> feat: 🎸 Added Polish language

- packages/app/components/absence.component.tsx
- packages/app/translations/en.json
- packages/app/translations/sv.json
Translation in report absence was incomplete
> Fixed missing translation in absence

- packages/site/.gitignore
- packages/site/next-sitemap.js
- packages/site/package.json
- packages/site/yarn.lock
A first attempt at improving SEO. I know nothing about next.js so this may be completely broken for all I know, but it works when running `yarn dev`.
> Try to improve SEO by generating robots.txt and sitemap.xml.

- packages/site/components/TimelineLatest.tsx
småredigeirngar + lagt till polisanmälan.
> chore: update timeline

- packages/site/components/Link.tsx
- packages/site/data/timelineEvents.tsx
!Behöver hjälp med: länka QA i aprilsammanfattningen till vår QA-sida.
Lagt till media:
- DN, Sweclockers (2 artiklar)
Lag till Viktiga händelser: 
- april och mars: datum och Holmdahls brev om avpublicering + borttagning av källkod
- april: Polisanmälan
- april: Axboms artikel
- i feb: när kommunen mottar Certezzas utredning
> chore: udate timeline

- packages/site/components/Banner.tsx
- packages/site/components/Footer.tsx
- packages/site/components/FunFacts.tsx
- packages/site/components/Header.tsx
- packages/site/components/Section.tsx
- packages/site/styles/global.css
This fixes some appearance issues when resizing window or using the site on a tablet, maybe not 100% fixed but a lot better.
> chore(site): update tablet styling

- README.md
_That's_ how you do strikethrough
> doc: Strikethrough

- packages/site/components/Banner.tsx
| ![Skärmavbild 2021-04-23 kl  14 53 48](https://user-images.githubusercontent.com/1478102/115873874-c3d1c200-a443-11eb-92d2-66aed1967b6d.png) | ![Skärmavbild 2021-04-23 kl  14 53 35](https://user-images.githubusercontent.com/1478102/115873866-c16f6800-a443-11eb-8ee5-d2215f553850.png) |
> fix(site): screenshot alignment

- packages/app/components/navigation.component.tsx
- packages/app/hooks/useAppState.tsx
- packages/app/package.json
- packages/app/yarn.lock
* Tracks if the app has been put to background or foreground
* Verifies if the user is valid when going into foreground
> feat: 🎸 Added useAppState hook and logs out user if not authenticated

- packages/app/components/__tests__/NewsItem.test.js
- packages/app/components/absence.component.tsx
- packages/app/components/newsItem.component.tsx
> Use moment's locale specific formats

- package-lock.json
- packages/app/components/week.component.tsx
- packages/app/index.js
- packages/app/services/languageService.ts
- packages/app/translations/en.json
- packages/app/translations/sv.json
- packages/app/utils/translation.ts
* removed package-lock.json that was accidently commited in
* added back LanguageService.getLocale() to useTimeTable
* translated some strings in schedule
> Added locale when fetching using useTimetable + translations

- packages/app/components/transitionView.component.tsx
- packages/app/components/week.component.tsx
- packages/app/package.json
- packages/app/yarn.lock
Apparently the ViewPager component does not like when you set the selectedIndex from the useEffect method. This is a workaround.
> fix: 🐛 Fixes crash in ViewPager when setting selectedIndex

- packages/app/components/absence.component.tsx
- packages/app/components/child.component.tsx
- packages/app/components/children.component.tsx
- packages/app/components/newsItem.component.tsx
- packages/app/components/saveToCalendar.component.tsx
- packages/app/components/week.component.tsx
Set some maxFontSizeMultipliers so we don't block UI functions. Screenshots are max scale on iphone
Closes #360
> Hyphenation issues

- packages/app/components/__tests__/Absence.test.js
- packages/app/components/__tests__/Children.test.js
- packages/app/components/__tests__/ContactMenu.test.js
- packages/app/components/__tests__/Menu.test.js
- packages/app/components/__tests__/NewsItem.test.js
- packages/app/components/__tests__/saveToCalendar.test.js
- packages/app/components/absence.component.tsx
- packages/app/components/contactMenu.component.tsx
- packages/app/components/newsItem.component.tsx
- packages/app/components/saveToCalendar.component.tsx
När översättningar ändras går tester sönder. Det här är en början på att göra testerna mindre känsliga.
> feat: 🎸 Make tests less fragile when changing translations

- packages/app/components/calendar.component.tsx
> fix: 🐛 Fixes background color issue when calender items is empt

- packages/app/components/absence.component.tsx
- packages/app/components/icon.component.tsx
> fix: 🐛 Added Alert Icon when personal number is wrong

- packages/app/components/auth.component.tsx
- packages/app/components/setLanguage.component.tsx
- packages/app/utils/translation.ts
> feat: 🎸 Added current language name to auth screen

- packages/app/.eslintrc.json
- packages/app/components/absence.component.tsx
- packages/app/components/auth.component.tsx
- packages/app/components/childListItem.component.tsx
- packages/app/components/children.component.tsx
- packages/app/components/contactMenu.component.tsx
- packages/app/components/image.component.tsx
- packages/app/components/login.component.tsx
- packages/app/components/markdown.component.tsx
- packages/app/components/menu.component.tsx
- packages/app/components/newsItem.component.tsx
- packages/app/components/newsList.component.tsx
- packages/app/components/newsListItem.component.tsx
- packages/app/components/saveToCalendar.component.tsx
- packages/app/package.json
- packages/app/translations/en.json
- packages/app/translations/sv.json
- packages/app/yarn.lock
* Added eslint-plugin-react-native-a11y
* Fixes lint errors produced by this linting tool
> fix: 🐛 add a11y lint and fix errors

- packages/app/components/login.component.tsx
use modal for login method picker. Fixes #404
✅ Closes: #404
> fix: 🐛 use modal for login method picker. Fixes #404

- packages/app/components/childListItem.component.tsx
Add accessibilityLabel and accessibilityRole for each item in the child list
✅ Closes: #354
> fix: 🐛 add a11y properties for childListItems

- packages/app/components/saveToCalendar.component.tsx
> fix: 🐛 Kalender - text blir avklippt

- packages/app/utils/SMS.js
Update the phoneNr to the correct one
> Update phone nr

- packages/app/components/children.component.tsx
- packages/app/components/newsItem.component.tsx
- packages/app/index.js
- packages/app/react-native.config.js
- packages/app/styles/typography.ts
Fixar vit navbar i darkmode #432
> Fix/after layout: Vit navbar i dark mode

- packages/app/components/login.component.tsx
> fix: 🐛 Ta bort avbryt från listan vid login

- packages/app/components/child.component.tsx
* Added child title to each subpage
> Add child title to subpages

- packages/app/components/newsListItem.component.tsx
* Switch to pressable (new in RN 0.63) instead of touchable opacity fixes this issue
> Switched to pressable instead of touchableopacity

- packages/app/components/auth.component.tsx
* Added hitSlop to increase touch area, switched to touchablewithoutfeedback
> fix: 🐛 Added hitslop to language button to increase touch area

- packages/app/package.json
- packages/app/yarn.lock
> fix: 🐛 Bump embedded-api to 5.2.0

- packages/app/android/app/build.gradle
Bump the verisonCode and versionName for Android to 2.0.0
> feat: 🎸 release 2.0.0 for Android

- packages/app/components/absence.component.tsx
- packages/app/components/child.component.tsx
- packages/app/components/childListItem.component.tsx
- packages/app/components/children.component.tsx
- packages/app/components/daySummary.component.tsx
- packages/app/components/navigation.component.tsx
- packages/app/components/newsItem.component.tsx
- packages/app/components/newsListItem.component.tsx
- packages/app/components/notification.component.tsx
- packages/app/components/setLanguage.component.tsx
- packages/app/components/tabBarLabel.component.tsx
- packages/app/design/dark.json
- packages/app/design/light.json
- packages/app/design/mapping.json
- packages/app/design/navigationThemes.ts
Fixade det mesta i #457 förutom namnet på barnet. Ska kika på det i en separat PR.
> fix: update colors to reach AAA

- packages/site/components/FunFacts.tsx
Maybe we should write a script to keep these updated upon deployment.
> fix: Update some outdated metrics

- apps/skolplattformen-sthlm/components/login.component.tsx
Much better than the greyish backdrop that we use now
> feat: 🎸 Use fade on the backdrop on login modal

- README.md
given url (without https//) returns 404
> Update README.md to remove a 404 link

- apps/skolplattformen-sthlm/components/__tests__/ContactMenu.test.js
- libs/api-skolplattformen/lib/parse/news.ts
- libs/api-skolplattformen/lib/parseHtml.ts
> fix: 🐛 Förhindrar krasch när Nyhetsbrev inte har något innehåll

- apps/skolplattformen-sthlm/components/absence.component.tsx
- apps/skolplattformen-sthlm/translations/en.json
- apps/skolplattformen-sthlm/translations/pl.json
- apps/skolplattformen-sthlm/translations/sv.json
> fix: 🐛 Klargör vems personnummer man ska fylla i på frånvaroanmälan

- apps/website/components/Privacy.tsx
- apps/website/components/QA.tsx
Updates QA page with spacing before links and some language fixes on the privacy page.
Supersedes #512, #513
> chore: language fixes

- apps/skolplattformen-sthlm/components/notification.component.tsx
> Make clicking on a notification open it in a webview to hjärntorget

- apps/skolplattformen-app/components/login.component.tsx
- apps/skolplattformen-app/components/settings.component.tsx
Until we have a better cache-clearing function in hooks lib this will
help with not filling the phone with old data
> feat: 🎸 Clear personal cache on login and logout

- apps/website/components/Privacy.tsx
- apps/website/components/featureData.tsx
> WEB: Include Gbg when we talk about supported platforms

- apps/website/components/PricingTemp.tsx
> Fix: Inconsistent pricing (last one)

- apps/skolplattformen-app/components/childListItem.component.tsx
The menu for next week are not available until monday morning (with current api implementation)
> feat: Hide lunch menu on weekends

- apps/skolplattformen-app/components/daySummary.component.tsx
- apps/skolplattformen-app/components/week.component.tsx
Fixar sortering av lektioner i dagliga summeringen och schemat.
✅ Closes: #591
> fix: 🐛 Felaktig sortering av lektioner

- apps/skolplattformen-app/data/schoolPlatforms.ts
> Fix stadsnamn

- apps/skolplattformen-app/android/build.gradle
Try this in order to fix build
> chore: 🤖 kotlinVersion in build.gradle

- docs/ios_mac.md
> chore(docs): update ios_mac.md
